version: "3.4"
services:
  gifmaker:
    image: jff/gifmaker:latest
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./images
        target: /images
    command: ["./*.png"]